services:

  backend:
    build:
      context: ./backend

    container_name: reviewmate_backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./backend:/app


  worker:
    build:
      context: ./backend

    container_name: reviewmate_worker

    command: rq worker reviewmate --url redis://redis:6379

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./backend:/app


  postgres:
    image: postgres:17

    container_name: reviewmate_postgres

    environment:
      POSTGRES_DB: reviewmate_db
      POSTGRES_USER: reviewmate_user
      POSTGRES_PASSWORD: reviewmate_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine

    container_name: reviewmate_redis

    ports:
      - "6379:6379"


volumes:
  postgres_data: